CHARACTER_ROLE_LEADER  = 'leader';
CHARACTER_ROLE_FIGHTER = 'fighter';
CHARACTER_ROLE_SCOUT   = 'scout';
CHARACTER_ROLE_HEALER  = 'healer';

module.exports = [
  CHARACTER_ROLE_LEADER,
  CHARACTER_ROLE_FIGHTER,
  CHARACTER_ROLE_SCOUT,
  CHARACTER_ROLE_HEALER
]
