CHARACTER_STAT_FEROCITY   = 'ferocity';
CHARACTER_STAT_ENDURANCE  = 'endurance';
CHARACTER_STAT_QUICKNESS  = 'quickness';
CHARACTER_STAT_RESILIENCE = 'resilience';

module.exports = [
  CHARACTER_STAT_FEROCITY,
  CHARACTER_STAT_ENDURANCE,
  CHARACTER_STAT_QUICKNESS,
  CHARACTER_STAT_RESILIENCE
]
